name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Debug_VK:
    name: "Debug_VK"
    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DANKI_EXTRA_CHECKS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

  Debug_D3D:
    name: "Debug_D3D"
    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DANKI_EXTRA_CHECKS=ON -DANKI_GR_BACKEND=DIRECTX

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

  Release_VK:
    name: "Release_VK"
    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

  Release_D3D:
    name: "Release_D3D"
    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF -DANKI_GR_BACKEND=DIRECTX

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

  DLSS:
    name: "DLSS"
    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF -DANKI_DLSS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target Sponza
